Add unit tests for ideal.sylph.controller.utils.JsonFormatUtil
Diffblue-benchmarks/Harbby-sylph pull request #1
Opened 2019-05-30 15:26 UTC by ThomasPerkins1123

Hi,

I've analysed your code base and noticed that `ideal.sylph.controller.utils.JsonFormatUtil` in the `sylph-controller` module is not fully tested.

I've written some tests that cover this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.

2019-05-30 15:41 UTC, petersear approved these changes

2019-05-30 15:47 UTC, EricHetti approved these changes

2019-05-31 07:58 UTC, paulkennethkent requested changes

2019-05-31 07:58 UTC, paulkennethkent commented on sylph-controller/src/test/java/ideal/sylph/controller/utils/JsonFormatUtilTest.java
> +package ideal.sylph.controller.utils;
Looking at the other files this might require a licence header

2019-05-31 07:58 UTC, paulkennethkent commented on sylph-controller/src/test/java/ideal/sylph/controller/utils/JsonFormatUtilTest.java
> +package ideal.sylph.controller.utils;
see https://github.com/harbby/sylph/blob/master/sylph-controller/src/main/java/ideal/sylph/controller/utils/JsonFormatUtil.java

2019-05-31 10:03 UTC, paulkennethkent approved these changes

2019-07-23 14:30 UTC, merged